MODEL:
  TYPE: AutoFormer
  NUM_CLASSES: 100
  DROP_PATH_RATE: 0.1
AT:
  GRAPH_TYPE: i3n303
  UNARY_OP: [[16], [0, 13], [0, 25], [6], [0], [25, 0]]
  BINARY_OP: [6, 3, 2]
AUTOFORMER:
  DEPTH: 13
  HIDDEN_DIM: 192
  MLP_RATIO:
  - 3.5
  - 3.5
  - 3.0
  - 3.5
  - 3.0
  - 3.0
  - 4.0
  - 4.0
  - 3.5
  - 4.0
  - 3.5
  - 4.0
  - 3.5
  NUM_HEADS:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 4
  - 3
  - 3
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False




