MODEL:
  TYPE: AutoAtten_pvt_v2_b0
  NUM_CLASSES: 100
  DROP_PATH_RATE: 0.1
  STAGE_ATTN_TYPE: AAAA
AT:
  binary_op:
  - 6
  - 3
  - 2
  graph_type: i3n303
  unary_op:
  - - 16
  - - 0
    - 13
  - - 0
    - 25
  - - 6
  - - 0
  - - 25
    - 0
PVT:
  LA_SR_RATIOS: 1111
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False




